FROM golang:1.26-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-w -s" -o /operator ./cmd/operator

FROM gcr.io/distroless/static-debian12
COPY --from=build /operator /operator
ENTRYPOINT ["/operator"]
