{{- if and .Values.zfsAgent.token (not .Values.zfsAgent.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "branchdb.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "branchdb.labels" . | nindent 4 }}
type: Opaque
stringData:
  zfsagent-token: {{ .Values.zfsAgent.token | quote }}
{{- end }}
